on:
  repository_dispatch:
    types: [http4k-release]
jobs:
  release-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - run: ./gradlew -i dokkaHtmlMultiModule
      - uses: actions/checkout@v2
        with:
          repository: http4k/api
          path: tmp
          token: ${{ secrets.AUTHOR_TOKEN }}
      - run: cp -R build/ddoc/http4k/* tmp/
      - uses: EndBug/add-and-commit@v4
        with:
          cwd: 'tmp'
          message: 'release API docs'
        env:
          GITHUB_TOKEN: ${{ secrets.AUTHOR_TOKEN }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTHOR_TOKEN }}
          directory: tmp
          repository: http4k/api
