name: "Security - Dependency Analysis (dependabot)"
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**/*.md'
  schedule:
    - cron: '0 12 * * 3' # ever
jobs:
  build:
    name: Dependencies
    runs-on: ubuntu-latest
    if: github.repository == 'http4k/http4k'
    permissions:
      contents: write
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4.2.2

      - uses: actions/setup-java@v4.7.0
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/actions/setup-gradle@v3
        with:
          dependency-graph: generate-and-submit
