name: Publish LTS Artifacts
on:
  push:
  repository_dispatch:
    types: [http4k-lts-release]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  ReleaseLTS:
    runs-on: ubuntu-latest
    if: github.repository == 'http4k/http4k'
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
      - name: Grab tag name
        uses: olegtarasov/get-tag@v2.1.3
        id: tagName
      - name: Setup Java
        uses: actions/setup-java@v4.4.0
        with:
          distribution: temurin
          java-version: 21
          cache: gradle
      - name: Upload to LTS
        run: |
          ./gradlew publish \
            -Psign=true \
            -PreleaseVersion="${{ github.event.client_payload.version }}" \
            -PsigningKey="${{ secrets.SIGNING_KEY }}" \
            -PsigningPassword="${{ secrets.SIGNING_PASSWORD }}" \
            -PltsUsername="${{ secrets.LTS_USERNAME }}" \
            -PltsPassword="${{ secrets.LTS_PASSWORD }}"
